apiVersion: v1
data:
  mysql_user.sh: |
    #!/bin/bash
    set -e

    mysql -v --user=root --password=${MYSQL_ROOT_PASSWORD} <<-EOSQL
      CREATE DATABASE ${USERS_SERVICE_DB_NAME};
      CREATE USER ${USERS_SERVICE_DB_USER} IDENTIFIED BY '${USERS_SERVICE_DB_PASS}';
      GRANT ALL PRIVILEGES on *.* TO '${USERS_SERVICE_DB_USER}';

      FLUSH PRIVILEGES;
    EOSQL
kind: ConfigMap
metadata:
  name: mysql-db-bootstrap
