apiVersion: v1
data:
  mysql_user.sh: |
    #!/bin/bash
    set -e

    mysql -v --user=root --password=${MYSQL_ROOT_PASSWORD} <<-EOSQL
      CREATE DATABASE ${USERS_SERVICE_DB_NAME};
      CREATE USER ${USERS_SERVICE_DB_USER} IDENTIFIED BY '${USERS_SERVICE_DB_PASS}';
      GRANT ALL PRIVILEGES on *.* TO '${USERS_SERVICE_DB_USER}';

      CREATE DATABASE ${CONTENT_SERVICE_DB_NAME};
      CREATE USER '${CONTENT_SERVICE_DB_USER}' IDENTIFIED BY '${CONTENT_SERVICE_DB_PASS}';
      GRANT ALL PRIVILEGES on *.* TO '${CONTENT_SERVICE_DB_USER}';

      CREATE DATABASE ${COMMUNITY_FORUM_SERVICE_DB_NAME};
      CREATE USER '${COMMUNITY_FORUM_SERVICE_DB_USER}' IDENTIFIED BY '${COMMUNITY_FORUM_SERVICE_DB_PASS}';
      GRANT ALL PRIVILEGES on *.* TO '${COMMUNITY_FORUM_SERVICE_DB_USER}';

      CREATE DATABASE ${FEEDBACK_SERVICE_DB_NAME};
      CREATE USER '${FEEDBACK_SERVICE_DB_USER}' IDENTIFIED BY '${FEEDBACK_SERVICE_DB_PASS}';
      GRANT ALL PRIVILEGES on *.* TO '${FEEDBACK_SERVICE_DB_USER}';

      CREATE DATABASE ${HELIX_DB_NAME};
      CREATE USER '${HELIX_DB_USER}' IDENTIFIED BY '${HELIX_DB_PASS}';
      GRANT ALL PRIVILEGES on *.* TO '${HELIX_DB_USER}';

      CREATE DATABASE ${HELIX_EDGE_DB_NAME};
      GRANT ALL PRIVILEGES on *.* TO '${HELIX_DB_USER}';

      CREATE DATABASE ${HELPDESK_SERVICE_DB_NAME};
      CREATE USER '${HELPDESK_SERVICE_DB_USER}' IDENTIFIED BY '${HELPDESK_SERVICE_DB_PASS}';
      GRANT ALL PRIVILEGES on *.* TO '${HELPDESK_SERVICE_DB_USER}';

      CREATE DATABASE ${NOTIFICATIONS_SERVICE_DB_NAME};
      CREATE USER '${NOTIFICATIONS_SERVICE_DB_USER}' IDENTIFIED BY '${NOTIFICATIONS_SERVICE_DB_PASS}';
      GRANT ALL PRIVILEGES on *.* TO '${NOTIFICATIONS_SERVICE_DB_USER}';

      CREATE DATABASE ${TRANSLATION_SERVICE_DB_NAME};
      CREATE USER '${TRANSLATION_SERVICE_DB_USER}' IDENTIFIED BY '${TRANSLATION_SERVICE_DB_PASS}';
      GRANT ALL PRIVILEGES on *.* TO '${TRANSLATION_SERVICE_DB_USER}';

      CREATE DATABASE ${USERS_SERVICE_DB_NAME};
      CREATE USER '${USERS_SERVICE_DB_USER}' IDENTIFIED BY '${USERS_SERVICE_DB_PASS}';
      GRANT ALL PRIVILEGES on *.* TO '${USERS_SERVICE_DB_USER}';

      CREATE DATABASE ${VISTIOR_REGISTRATION_DB_NAME};
      CREATE USER '${VISTIOR_REGISTRATION_DB_USER}' IDENTIFIED BY '${VISTIOR_REGISTRATION_DB_PASS}';
      GRANT ALL PRIVILEGES on *.* TO '${VISTIOR_REGISTRATION_DB_USER}';
      FLUSH PRIVILEGES;
    EOSQL
kind: ConfigMap
metadata:
  name: mysql-db-bootstrap
