{{- if .Values.pvc.enabled -}}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-pvc
spec:
  storageClassName: aws
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
{{- end -}}
