apiVersion: v1
data:
  db_root_pass: {{ .Values.db_root_pass | b64enc }}
  db_admin_pass: {{ .Values.db_admin_pass | b64enc }}
  db_admin_user: {{ .Values.db_admin_user | b64enc }}
  users_service_db_pass: {{ .Values.users_service_db_pass | b64enc }}
  users_service_db_user: {{ .Values.users_service_db_user | b64enc }}
  users_service_db_name: {{ .Values.users_service_db_name | b64enc }}
kind: Secret
metadata:
  name: mysql-db-creds
type: Opaque
