apiVersion: v1
data:
  db_root_pass: {{ .Values.db_root_pass | b64enc }}
  db_admin_pass: {{ .Values.db_admin_pass | b64enc }}
  db_admin_user: {{ .Values.db_admin_user | b64enc }}
  community_forum_service_db_pass: {{ .Values.community_forum_service_db_pass | b64enc }}
  community_forum_service_db_user: {{ .Values.community_forum_service_db_user | b64enc }}
  community_forum_service_db_name: {{ .Values.community_forum_service_db_name | b64enc }}
  content_service_db_pass: {{ .Values.content_service_db_pass | b64enc }}
  content_service_db_user: {{ .Values.content_service_db_user | b64enc }}
  content_service_db_name: {{ .Values.content_service_db_name | b64enc }}
  feedback_service_db_pass: {{ .Values.feedback_service_db_pass | b64enc }}
  feedback_service_db_user: {{ .Values.feedback_service_db_user | b64enc }}
  feedback_service_db_name: {{ .Values.feedback_service_db_name | b64enc }}
  helix_db_pass: {{ .Values.helix_db_pass | b64enc }}
  helix_db_user: {{ .Values.helix_db_user | b64enc }}
  helix_db_name: {{ .Values.helix_db_name | b64enc }}
  helix_edge_db_pass: {{ .Values.helix_edge_db_pass | b64enc }}
  helix_edge_db_user: {{ .Values.helix_edge_db_user | b64enc }}
  helix_edge_db_name: {{ .Values.helix_edge_db_name | b64enc }}
  helpdesk_service_db_pass: {{ .Values.helpdesk_service_db_pass | b64enc }}
  helpdesk_service_db_user: {{ .Values.helpdesk_service_db_user | b64enc }}
  helpdesk_service_db_name: {{ .Values.helpdesk_service_db_name | b64enc }}
  notifications_service_db_pass: {{ .Values.notifications_service_db_pass | b64enc }}
  notifications_service_db_user: {{ .Values.notifications_service_db_user | b64enc }}
  notifications_service_db_name: {{ .Values.notifications_service_db_name | b64enc }}
  translation_service_db_pass: {{ .Values.translation_service_db_pass | b64enc }}
  translation_service_db_user: {{ .Values.translation_service_db_user | b64enc }}
  translation_service_db_name: {{ .Values.translation_service_db_name | b64enc }}
  users_service_db_pass: {{ .Values.users_service_db_pass | b64enc }}
  users_service_db_user: {{ .Values.users_service_db_user | b64enc }}
  users_service_db_name: {{ .Values.users_service_db_name | b64enc }}
  visitor_registration_service_db_pass: {{ .Values.visitor_registration_service_db_pass | b64enc }}
  visitor_registration_service_db_user: {{ .Values.visitor_registration_service_db_user | b64enc }}
  visitor_registration_service_db_name: {{ .Values.visitor_registration_service_db_name | b64enc }}
kind: Secret
metadata:
  name: mysql-db-creds
type: Opaque
