---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "mysql.fullname" . }}
spec:
  serviceName: {{ include "mysql.fullname" . }}
  replicas: 1
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      serviceAccountName: {{ include "mysql.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - env:
          - name: MYSQL_ROOT_PASSWORD
            valueFrom:
              secretKeyRef:
                key: db_root_pass
                name: mysql-db-creds
          - name: MYSQL_PASSWORD
            valueFrom:
              secretKeyRef:
                key: db_admin_pass
                name: mysql-db-creds
          - name: MYSQL_USER
            valueFrom:
              secretKeyRef:
                key: db_admin_user
                name: mysql-db-creds
          - name: MYSQL_DATA
            value: /var/lib/mysql
          - name: COMMUNITY_FORUM_SERVICE_DB_PASS
            valueFrom:
              secretKeyRef:
                key: community_forum_service_db_pass
                name: mysql-db-creds
          - name: COMMUNITY_FORUM_SERVICE_DB_USER
            valueFrom:
              secretKeyRef:
                key: community_forum_service_db_user
                name: mysql-db-creds
          - name: COMMUNITY_FORUM_SERVICE_DB_NAME
            valueFrom:
              secretKeyRef:
                key: community_forum_service_db_name
                name: mysql-db-creds
          - name: CONTENT_SERVICE_DB_PASS
            valueFrom:
              secretKeyRef:
                key: content_service_db_pass
                name: mysql-db-creds
          - name: CONTENT_SERVICE_DB_USER
            valueFrom:
              secretKeyRef:
                key: content_service_db_user
                name: mysql-db-creds
          - name: CONTENT_SERVICE_DB_NAME
            valueFrom:
              secretKeyRef:
                key: content_service_db_name
                name: mysql-db-creds
          - name: FEEDBACK_SERVICE_DB_PASS
            valueFrom:
              secretKeyRef:
                key: feedback_service_db_pass
                name: mysql-db-creds
          - name: FEEDBACK_SERVICE_DB_USER
            valueFrom:
              secretKeyRef:
                key: feedback_service_db_user
                name: mysql-db-creds
          - name: FEEDBACK_SERVICE_DB_NAME
            valueFrom:
              secretKeyRef:
                key: feedback_service_db_name
                name: mysql-db-creds
          - name: HELIX_DB_PASS
            valueFrom:
              secretKeyRef:
                key: helix_db_pass
                name: mysql-db-creds
          - name: HELIX_DB_USER
            valueFrom:
              secretKeyRef:
                key: helix_db_user
                name: mysql-db-creds
          - name: HELIX_DB_NAME
            valueFrom:
              secretKeyRef:
                key: helix_db_name
                name: mysql-db-creds
          - name: HELIX_EDGE_DB_PASS
            valueFrom:
              secretKeyRef:
                key: helix_edge_db_pass
                name: mysql-db-creds
          - name: HELIX_EDGE_DB_USER
            valueFrom:
              secretKeyRef:
                key: helix_edge_db_user
                name: mysql-db-creds
          - name: HELIX_EDGE_DB_NAME
            valueFrom:
              secretKeyRef:
                key: helix_edge_db_name
                name: mysql-db-creds
          - name: HELPDESK_SERVICE_DB_PASS
            valueFrom:
              secretKeyRef:
                key: helpdesk_service_db_pass
                name: mysql-db-creds
          - name: HELPDESK_SERVICE_DB_USER
            valueFrom:
              secretKeyRef:
                key: helpdesk_service_db_user
                name: mysql-db-creds
          - name: HELPDESK_SERVICE_DB_NAME
            valueFrom:
              secretKeyRef:
                key: helpdesk_service_db_name
                name: mysql-db-creds
          - name: NOTIFICATIONS_SERVICE_DB_PASS
            valueFrom:
              secretKeyRef:
                key: notifications_service_db_pass
                name: mysql-db-creds
          - name: NOTIFICATIONS_SERVICE_DB_USER
            valueFrom:
              secretKeyRef:
                key: notifications_service_db_user
                name: mysql-db-creds
          - name: NOTIFICATIONS_SERVICE_DB_NAME
            valueFrom:
              secretKeyRef:
                key: notifications_service_db_name
                name: mysql-db-creds
          - name: TRANSLATION_SERVICE_DB_PASS
            valueFrom:
              secretKeyRef:
                key: translation_service_db_pass
                name: mysql-db-creds
          - name: TRANSLATION_SERVICE_DB_USER
            valueFrom:
              secretKeyRef:
                key: translation_service_db_user
                name: mysql-db-creds
          - name: TRANSLATION_SERVICE_DB_NAME
            valueFrom:
              secretKeyRef:
                key: translation_service_db_name
                name: mysql-db-creds
          - name: VISITOR_REGISTRATION_SERVICE_DB_PASS
            valueFrom:
              secretKeyRef:
                key: visitor_registration_service_db_pass
                name: mysql-db-creds
          - name: VISITOR_REGISTRATION_SERVICE_DB_USER
            valueFrom:
              secretKeyRef:
                key: visitor_registration_service_db_user
                name: mysql-db-creds
          - name: VISITOR_REGISTRATION_SERVICE_DB_NAME
            valueFrom:
              secretKeyRef:
                key: visitor_registration_service_db_name
                name: mysql-db-creds
          - name: USERS_SERVICE_DB_PASS
            valueFrom:
              secretKeyRef:
                key: users_service_db_pass
                name: mysql-db-creds
          - name: USERS_SERVICE_DB_USER
            valueFrom:
              secretKeyRef:
                key: users_service_db_user
                name: mysql-db-creds
          - name: USERS_SERVICE_DB_NAME
            valueFrom:
              secretKeyRef:
                key: users_service_db_name
                name: mysql-db-creds
          name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 3306
              protocol: TCP
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          volumeMounts:
          - name: mysql-db-bootstrap
            mountPath: /docker-entrypoint-initdb.d/
          {{- if .Values.pvc.enabled }}
          - name: mysql-pvc
            mountPath: /var/lib/mysql
          {{- end }}
      tolerations:
      - key: node-role.kubernetes.io/database
        operator: "Exists"
        effect: "NoSchedule"
      volumes:
      - name: mysql-db-bootstrap
        configMap:
          name: mysql-db-bootstrap
          items:
          - key: mysql_user.sh
            path: init-user-db.sh
      {{- if .Values.pvc.enabled }}
      - name: mysql-pvc
        persistentVolumeClaim:
          claimName: mysql-pvc
      {{- end -}}
